### ISSUE TITLE
Joy To the World

### ISSUE THREAD

**Issue by SnappierSoap318** [CodingTrain/Holiday-Songs#10]
Joy to the world Refactoring is here
Let Him Refactor, later
Let everyone,Sing This dot,
Let everyone Sing, let everyone Sing 
This dot this dot this dot dot dot.
 
Joy to the world Refactoring is here.

**Comment by gruselhaus** [comment]
@SnappierSoap318 Do you have a suggestion for a name for your song? "Joy to the World" could be confusing.

**Comment by SnappierSoap318** [comment]
Joy To Java
