### ISSUE TITLE
Oh Coding Train

### ISSUE THREAD

**Issue by arandomtim** [CodingTrain/Holiday-Songs#18]
Oh Coding Train, Oh Coding Train
How lovely are your challenges

There's perlin noise, and Processing
p5.js, and machine learning

Oh Coding Train, Oh Coding Train
How lovely are your challenges

**Comment by gruselhaus** [comment]
https://github.com/CodingTrain/Holiday-Songs/blob/master/OhCodingTrain.md

**Comment by gruselhaus** [comment]
Thank you for this contribution ⛄️
