### ISSUE TITLE
Your missing this dot( feliz Navidad )

### ISSUE THREAD

**Issue by Xyloking17** [CodingTrain/Holiday-Songs#29]
[C]    [D]
Your Missing This Dot,
                             [G]    [Em]
Your Missing This Dot,
                             [C]              [D]                                         [G]
Your Missing This Dot, Better Correct it or your code wont run.
                                  [C]
I want to wish you all happy coding,
[D]                             [G]
I want to wish you all happy coding,
[Em]                           [C]
I want to wish you all happy coding,
       [D]                    [G]
and easy re-fact-or-ing.

**Comment by gruselhaus** [comment]
472d398b29c010ee96ecc8aebe2902ee3b5603e0
9275c8916035566cc7ed77950450a25998edcb06
