### ISSUE TITLE
O code all ye faithful

### ISSUE THREAD

**Issue by jasondunken** [CodingTrain/Holiday-Songs#5]
O code, all ye faithful
Download and get a coding
O code ye, o code ye in Processing!
Code and write functions
draw some animations!
O code, let us debug them
O code, let us debug them
O code, let us debug them
Dan is the man!
O code, all ye faithful
O code, all ye faithful
O code, all ye faithful in Processing!
O code, all ye faithful
O code, all ye faithful
O code, all ye faithful in Processing!

**Comment by gruselhaus** [comment]
❤️
