### ISSUE TITLE
JINGLE BELLS

### ISSUE THREAD

**Issue by sjoerd1999** [CodingTrain/Holiday-Songs#8]
.•♫•♬• 𝕁𝕀ℕ𝔾𝕃𝔼 𝔹𝔼𝕃𝕃𝕊 •♬•♫•.

Dashing through the code
In the Processing IDE
Through the lines we go
Refactoring all the way.

Code is way too long
Making functions tight
What fun it is to make long code
A handful lines tonight.

Refactoring, refactoring,
Refactoring all the way,
Oh what fun it is to use
For-loops everywhere, ay,

Refactoring, refactoring,
Refactoring all the way,
Code is oh so short now,
With iterations and arrays

**Comment by gruselhaus** [comment]
@sjoerd1999 Do you have a suggestion for a name for your song? "Jingle Bells" could be confusing.

**Comment by sjoerd1999** [comment]
Refactoring all the way
